### ISSUE TITLE
Error: Cross origin null forbidden

### ISSUE THREAD

**Issue by sinisa-nimcevic** [chvarkov/google-recaptcha#116]
**Describe the bug**
When we use the ReCAPTCHA decorator in our NestJS app and the endpoint gets called we get the aforementioned error:
Error: Cross origin null forbidden

This is the stack trace:

`Error: Cross origin null forbidden 
  at dispatchError (/app/api/my-api/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:54:19) 
  at Object.validCORSHeaders (/app/api/go-grgeen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:66:5) 
  at receiveResponse (/app/api/my-api/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21) 
  at Request.<anonymous> (/app/api/my-api/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38) 
  at Request.emit (events.js:315:20) at Request.onRequestResponse (/app/api/my-api/node_modules/request/request.js:1059:10) 
  at ClientRequest.emit (events.js:327:22) 
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27) 
  at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17) 
  at TLSSocket.socketOnData (_http_client.js:479:22) undefined`

**Additional context**
We tried setting axios config like this and it doesn't work

`
GoogleRecaptchaModule.forRootAsync({ 
  imports: [ConfigModule], useFactory: (configService: ConfigService) => ({ secretKey: configService.get('app.recaptchaSecret'), 
    response: (req) => req.body.recaptchaValue, 
    skipIf: configService.get('app.backendUrl').startsWith('localhost'), 
    network: GoogleRecaptchaNetwork.Recaptcha, 
    axiosConfig: { 
      headers: { 'Access-Control-Allow-Origin': '*', // We also tried setting up specifically our domain here }, }, }), 
 inject: [ConfigService], }),`

**Comment by andrija29** [comment]
Hello @chvarkov Sinisa's colleague here.
When we comment out `@Recaptcha()` guard everything works fine.
Regarding the `debug: true` it gives same error without any additional logs.

**Comment by andrija29** [comment]
@chvarkov Express, HTTP. At the end we tried implementing it and Axios was hanging when sending requests to Google servers.
At the end I tried using really old and depreciated `request` package and it worked with it, but it didn't wanna work with Axios.

We are gonna mark this issue as resolved since it's Axios problem.
