### ISSUE TITLE
Error when using `GoogleRecaptchaGuard` or `@Recaptcha()` decorator

### ISSUE THREAD

**Issue by gmwill934** [chvarkov/google-recaptcha#92]
Hello

I have tried to implement recaptcha with this module but currently hitting a wall.

- Using the `GoogleRecaptchaGuard` by itself with `@UseGuards()`
- Using the `@Recaptcha()` decorator alone
- Using both 
```
@UseGuards(GoogleRecaptchaGuard)
  @Recaptcha()
  @Get('recaptcha')
  async recaptcha() {
    return true;
  } 
```

**The error**

```
TypeError: Cannot read properties of undefined (reading 'valid')
    at GoogleRecaptchaEnterpriseValidator.validate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestlab/src/services/validators/google-recaptcha-enterprise.validator.ts:36:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at GoogleRecaptchaGuard.canActivate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestlab/src/guards/google-recaptcha.guard.ts:41:39)
    at GuardsConsumer.tryActivate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
    at canActivateFn (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-execution-context.js:134:33)
    at /Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-execution-context.js:42:31
    at /Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-proxy.js:9:17

```

This is how I initialize this module on my **`app.module.ts`** file

```
GoogleRecaptchaModule.forRoot({
      response: (req: IncomingMessage) => {
        return (req.headers.recaptcha || '').toString();
      },
      actions: ['RegisterAccount'],
      score: 0.8,
      enterprise: {
        projectId: 'project-id',
        siteKey: 'site-key',
        apiKey: 'api-key',
      },
    }),
```

Inject on Interceptor so I can use it
```
constructor(
    private readonly mailService: MailService,
    private readonly recaptchaGoogleEnterprise: GoogleRecaptchaEnterpriseValidator,
  ) {}
```

Am I missing something? 

Thanks

**Comment by chvarkov** [comment]
Hi @gmwill934 , looks like it's bug in lib, could you set `debug: true` and show me logged response?

**Comment by gmwill934** [comment]
absolutely @chvarkov 
```
Nest] 27073  - 09/06/2022, 4:01:57 PM   DEBUG [GoogleRecaptchaEnterprise.request] Object:
{
  "body": {
    "event": {
      "siteKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "token": ""
    }
  }
}

[Nest] 27073  - 09/06/2022, 4:01:57 PM   DEBUG [GoogleRecaptchaEnterprise.response] Object:
{
  "name": "projects/40435629844/assessments/44b1a87b34000000",
  "event": {
    "token": "",
    "siteKey": "xxxxxxx",
    "userAgent": "",
    "userIpAddress": "",
    "expectedAction": "",
    "hashedAccountId": ""
  }
}

[Nest] 27073  - 09/06/2022, 4:01:57 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'valid')
TypeError: Cannot read properties of undefined (reading 'valid')
    at GoogleRecaptchaEnterpriseValidator.validate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestlab/src/services/validators/google-recaptcha-enterprise.validator.ts:36:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at GoogleRecaptchaGuard.canActivate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestlab/src/guards/google-recaptcha.guard.ts:41:39)
    at GuardsConsumer.tryActivate (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
    at canActivateFn (/Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-execution-context.js:134:33)
    at /Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-execution-context.js:42:31
    at /Users/gmwill934/Documents/tlantli/api/node_modules/@nestjs/core/router/router-proxy.js:9:17

```

**Comment by chvarkov** [comment]
@gmwill934 yes, I reproduced it, it's happening when you call your endpoint without `recaptcha` header.
Fixing now.

**Comment by chvarkov** [comment]
@gmwill934 The fix was published v3.1.6

**Comment by gmwill934** [comment]
Thank you so much!

**Comment by chvarkov** [comment]
@gmwill934 Yes, sure, you can generate on client side:

HTML:
```
<script src="https://www.google.com/recaptcha/enterprise.js?render=SITE_KEY"></script>

```

JS:
```
grecaptcha.enterprise.ready(async () => {
    const token = await grecaptcha.enterprise.execute('SITE_KEY', { action: 'RegisterAccount' });
    console.log('RecaptchaToken', token);
});
```
Or set `skipIf: !production`
